# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"FillMissing": "00_tabular.ipynb",
         "Categorize": "00_tabular.ipynb",
         "Normalize": "00_tabular.ipynb",
         "apply_procs": "00_tabular.ipynb",
         "TabularDataset": "00_tabular.ipynb",
         "tabular_learner": "00_tabular.ipynb"}

modules = ["tabular.py"]

doc_url = "https://muellerzr.github.io/fastinference_onnx/"

git_url = "https://github.com/muellerzr/fastinference_onnx/tree/master/"

def custom_doc_links(name): return None
